blank_issues_enabled: false
contact_links:
  - name: QMS Documentation
    url: https://drive.google.com/drive/folders/1Eu9d3qyJhFKQLRetTt92gkcDrTb7kjwo?usp=share_link
    about: Review QMS procedures and documentation
  - name: Support Email
    url: mailto:support@eiro.ai
    about: For customer complaints or urgent issues, email support@eiro.ai
